name: CD

on:
  push:
    branches: [main]

env:
  PORT: 5000
  DOCKER_IMAGE: 'aif-server'
  DOCKER_CONTAINER: 'aif-server'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v2

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Running WAS Container
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "OSRM_URI=${{ secrets.OSRM_URI }}" >> .env
          cat .env
          docker stop ${{ env.DOCKER_CONTAINER }} \
          && docker rm ${{ env.DOCKER_CONTAINER }}
          docker run -d -p ${{ env.PORT }}:3000 ${{ env.DOCKER_IMAGE }}:latest
